apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayang-kulit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayang-kulit
  template:
    metadata:
      labels:
        app: wayang-kulit
    spec:
      containers:
      - name: wayang-kulit
        image: rotua1005/wayang-kulit:latest  # Ganti sesuai nama Docker Hub Anda
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "root"
        - name: DB_NAME
          value: "Wayang Tales"
